name: Deploy to CloudBase Static Hosting

on:
  push:
    branches:
      - main # 只在main分支被推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新的Ubuntu虚拟机环境
    steps:
      - name: Checkout # 第一步：拉取你的代码
        uses: actions/checkout@v2

      - name: Install Node.js # 第二步：安装Node.js环境
        uses: actions/setup-node@v2
        with:
          node-version: '18' # 使用Node.js 18版本

      - name: Install Dependencies and Build # 第三步：安装依赖并打包
        env:
          # 把我们需要的API Key也注入到构建环境中
          VITE_ZHIPU_API_KEY: ${{ secrets.VITE_ZHIPU_API_KEY }}
        run: |
          npm install
          npm run build

      - name: Deploy to CloudBase # 第四步：部署到腾讯云
        uses: TencentCloud/tcb-action@v1.0.0
        with:
          secretId: ${{ secrets.TCB_SECRET_ID }}
          secretKey: ${{ secrets.TCB_SECRET_KEY }}
          envId: ${{ secrets.TCB_ENV_ID }}
          staticSrcPath: ./dist # 告诉它我们打包好的文件在dist目录